default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Hashira123_X
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default
  database: project_ecommerce

test:
  <<: *default
  database: project_ecommerce_test
